env:
  TERM: xterm-256color
  LANG: en_US.UTF-8
  LC_CTYPE: UTF-8
dynamic_title: true
font:
  normal:
    family: Fira Code
    style: Regular
  size: 11
  use_thin_strokes: true
colors:
  name: Atelierseaside (dark)
  author: Chris Kempson
  primary:
    background: "#131513"
    foreground: "#8ca68c"
  cursor:
    text: "#131513"
    cursor: "#8ca68c"
  normal:
    black: "#131513"
    red: "#e6193c"
    green: "#29a329"
    yellow: "#c3c322"
    blue: "#3d62f5"
    magenta: "#ad2bee"
    cyan: "#1999b3"
    white: "#8ca68c"
  bright:
    black: "#687d68"
    red: "#e6193c"
    green: "#29a329"
    yellow: "#c3c322"
    blue: "#3d62f5"
    magenta: "#ad2bee"
    cyan: "#1999b3"
    white: "#f0fff0"
background_opacity: 0.9
