auto_save.session = true
bindings.commands = {"insert": {"<Alt+Shift+u>": "spawn --userscript qute-keepassxc --key 0E7CD1EB9D4F92735B243D87E8A8E10DCB38E9BC"}, "normal": {",M": "hint links spawn mpv {hint-url}",
                                                                                                                                                 ",f": "fake-key f", ",m": "spawn mpv {url}", ",r": "config-source", ";1": "hint inputs --first", "pw": "spawn --userscript qute-keepassxc --key 0E7CD1EB9D4F92735B243D87E8A8E10DCB38E9BC"}}
colors.completion.category.bg =  # 2e2a31
colors.completion.category.border.bottom =  # 2e2a31
colors.completion.category.border.top =  # 2e2a31
colors.completion.category.fg =  # dc8a0e
colors.completion.even.bg =  # 2e2a31
colors.completion.fg =  # bcbabe
colors.completion.item.selected.bg =  # 666369
colors.completion.item.selected.border.bottom =  # 666369
colors.completion.item.selected.border.top =  # 666369
colors.completion.item.selected.fg =  # bcbabe
colors.completion.item.selected.match.fg =  # 17ad98
colors.completion.match.fg =  # 17ad98
colors.completion.odd.bg =  # 4a464d
colors.completion.scrollbar.bg =  # 2e2a31
colors.completion.scrollbar.fg =  # bcbabe
colors.contextmenu.disabled.bg =  # 4a464d
colors.contextmenu.disabled.fg =  # 9f9da2
colors.contextmenu.menu.bg =  # 2e2a31
colors.contextmenu.menu.fg =  # bcbabe
colors.contextmenu.selected.bg =  # 666369
colors.contextmenu.selected.fg =  # bcbabe
colors.downloads.bar.bg =  # 2e2a31
colors.downloads.error.fg =  # d8137f
colors.downloads.start.bg =  # 796af5
colors.downloads.start.fg =  # 2e2a31
colors.downloads.stop.bg =  # 149bda
colors.downloads.stop.fg =  # 2e2a31
colors.hints.bg =  # dc8a0e
colors.hints.fg =  # 2e2a31
colors.hints.match.fg =  # bcbabe
colors.keyhint.bg =  # 2e2a31
colors.keyhint.fg =  # bcbabe
colors.keyhint.suffix.fg =  # bcbabe
colors.messages.error.bg =  # d8137f
colors.messages.error.border =  # d8137f
colors.messages.error.fg =  # 2e2a31
colors.messages.info.bg =  # 2e2a31
colors.messages.info.border =  # 2e2a31
colors.messages.info.fg =  # bcbabe
colors.messages.warning.bg =  # bb60ea
colors.messages.warning.border =  # bb60ea
colors.messages.warning.fg =  # 2e2a31
colors.prompts.bg =  # 2e2a31
colors.prompts.border =  # 2e2a31
colors.prompts.fg =  # bcbabe
colors.prompts.selected.bg =  # 666369
colors.prompts.selected.fg =  # bcbabe
colors.statusbar.caret.bg =  # bb60ea
colors.statusbar.caret.fg =  # 2e2a31
colors.statusbar.caret.selection.bg =  # 796af5
colors.statusbar.caret.selection.fg =  # 2e2a31
colors.statusbar.command.bg =  # 2e2a31
colors.statusbar.command.fg =  # bcbabe
colors.statusbar.command.private.bg =  # 2e2a31
colors.statusbar.command.private.fg =  # bcbabe
colors.statusbar.insert.bg =  # 796af5
colors.statusbar.insert.fg =  # 2e2a31
colors.statusbar.normal.bg =  # 2e2a31
colors.statusbar.normal.fg =  # 17ad98
colors.statusbar.passthrough.bg =  # 149bda
colors.statusbar.passthrough.fg =  # 2e2a31
colors.statusbar.private.bg =  # 4a464d
colors.statusbar.private.fg =  # 2e2a31
colors.statusbar.progress.bg =  # 796af5
colors.statusbar.url.error.fg =  # d8137f
colors.statusbar.url.fg =  # bcbabe
colors.statusbar.url.hover.fg =  # bcbabe
colors.statusbar.url.success.http.fg =  # 149bda
colors.statusbar.url.success.https.fg =  # 17ad98
colors.statusbar.url.warn.fg =  # bb60ea
colors.tabs.bar.bg =  # 2e2a31
colors.tabs.even.bg =  # 2e2a31
colors.tabs.even.fg =  # bcbabe
colors.tabs.indicator.error =  # d8137f
colors.tabs.indicator.start =  # 796af5
colors.tabs.indicator.stop =  # 149bda
colors.tabs.odd.bg =  # 4a464d
colors.tabs.odd.fg =  # bcbabe
colors.tabs.pinned.even.bg =  # 149bda
colors.tabs.pinned.even.fg =  # f5f4f7
colors.tabs.pinned.odd.bg =  # 17ad98
colors.tabs.pinned.odd.fg =  # f5f4f7
colors.tabs.pinned.selected.even.bg =  # 666369
colors.tabs.pinned.selected.even.fg =  # bcbabe
colors.tabs.pinned.selected.odd.bg =  # 666369
colors.tabs.pinned.selected.odd.fg =  # bcbabe
colors.tabs.selected.even.bg =  # 6c5ce7
colors.tabs.selected.even.fg =  # FFFFFF
colors.tabs.selected.odd.bg =  # 6c5ce7
colors.tabs.selected.odd.fg =  # FFFFFF
colors.webpage.preferred_color_scheme = dark
content.blocking.adblock.lists = ["https://easylist.to/easylist/easylist.txt", "https://easylist.to/easylist/easyprivacy.txt", "https://easylist-downloads.adblockplus.org/easylistdutch.txt",
                                  "https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt", "https://www.i-dont-care-about-cookies.eu/abp/", "https://secure.fanboy.co.nz/fanboy-cookiemonster.txt"]
content.blocking.method = both
content.blocking.whitelist = ["beampipe.io", "*.takeaway.com", "*.instana.io",
                              "*.sentry.io", "cw-api.takeaway.com", "*.optimizely.com", "*.tiqcdn.com"]
https: // discord.com: content.desktop_capture = true
https: // gorillas.io: content.geolocation = true
https: // www.lieferando.de: content.geolocation = true
content.javascript.can_access_clipboard = true
https: // discord.com: content.media.audio_capture = true
https: // meet.ffmuc.net: content.media.audio_capture = true
https: // meet.jit.si: content.media.audio_capture = true
http: // localhost: 8080: content.notifications.enabled = true
https: // calendar.google.com: content.notifications.enabled = true
https: // developer.mozilla.org: content.notifications.enabled = true
https: // localmonero.co: content.notifications.enabled = true
https: // media.teich.3nt3.de: content.notifications.enabled = true
https: // old.reddit.com: content.notifications.enabled = true
https: // teams.microsoft.com: content.notifications.enabled = true
https: // web.telegram.im: content.notifications.enabled = true
https: // www.javascripttutorial.net: content.notifications.enabled = true
https: // www.reddit.com: content.notifications.enabled = true
https: // www.youtube.com: content.notifications.enabled = false
https: // calendar.google.com?cid = %25s: content.register_protocol_handler = true
fonts.default_size = 12pt
qt.force_platform = wayland
qt.highdpi = true
scrolling.smooth = true
tabs.min_width = -1
tabs.padding = {"bottom": 5, "left": 5, "right": 5, "top": 5}
tabs.position = left
tabs.width = 10%
zoom.default = 130
